// flow-typed signature: c7f7980f73e741869bf1030da3852130
// flow-typed version: <<STUB>>/redux-axios-middleware_v^4.0.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-axios-middleware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-axios-middleware' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-axios-middleware/dist/bundle' {
  declare module.exports: any;
}

declare module 'redux-axios-middleware/test/defaults' {
  declare module.exports: any;
}

declare module 'redux-axios-middleware/test/getActionTypes' {
  declare module.exports: any;
}

declare module 'redux-axios-middleware/test/middleware' {
  declare module.exports: any;
}

declare module 'redux-axios-middleware/test/test_helper' {
  declare module.exports: any;
}

declare module 'redux-axios-middleware/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-axios-middleware/dist/bundle.js' {
  declare module.exports: $Exports<'redux-axios-middleware/dist/bundle'>;
}
declare module 'redux-axios-middleware/test/defaults.js' {
  declare module.exports: $Exports<'redux-axios-middleware/test/defaults'>;
}
declare module 'redux-axios-middleware/test/getActionTypes.js' {
  declare module.exports: $Exports<'redux-axios-middleware/test/getActionTypes'>;
}
declare module 'redux-axios-middleware/test/middleware.js' {
  declare module.exports: $Exports<'redux-axios-middleware/test/middleware'>;
}
declare module 'redux-axios-middleware/test/test_helper.js' {
  declare module.exports: $Exports<'redux-axios-middleware/test/test_helper'>;
}
declare module 'redux-axios-middleware/webpack.config.js' {
  declare module.exports: $Exports<'redux-axios-middleware/webpack.config'>;
}
